[coreservice]
Host = "127.0.0.1"
Username = "root"
Password = "root"
Port = "3306"
Dbname = "SCC"
Redisip="127.0.0.1:6379"
Httpserverhost=":9888"
[sccwork]
Host = "127.0.0.1"
Username = "root"
Password = "root"
Port = "3306"
Dbname = "SCC"
Httpserverhost=":9980"
[sccfs]
Host = "127.0.0.1"
Username = "root"
Password = "root"
Port = "3306"
Dbname = "SCC"
Redisip="127.0.0.1:6379"
Httpserverhost=":19980"
Fsip="192.168.1.200"
Fsport="8021"
Fspssword="ClueCon"
RabbitMQIP="amqp://sjd:sjd@192.168.1.171:5672/admin"
[liveroom]
Host = "127.0.0.1"
Username = "root"
Password = "root"
Port = "3306"
Dbname = "SCC"
Redisip="127.0.0.1:6379"
Httpserverhost=":13460"
Httprequesturl="http://192.168.1.171:80/"
Secret="035c73f7-bb6b-4889-a715-d9eb2d1925cc"
[workdaping]
Host = "127.0.0.1"
Username = "root"
Password = "root"
Port = "3306"
Dbname = "sccwork"
Httpserverhost=":17888"
[commwork]
Host = "127.0.0.1"
Username = "root"
Password = "root"
Port = "3306"
Dbname = "scctask"
Httpserverhost=":9990"