// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: sjd.proto

package scc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SccIMPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messageid      *int32  `protobuf:"varint,1,req,name=messageid" json:"messageid,omitempty"`
	Fromsccid      *int32  `protobuf:"varint,2,req,name=fromsccid" json:"fromsccid,omitempty"`
	Tosccid        *int32  `protobuf:"varint,3,req,name=tosccid" json:"tosccid,omitempty"`
	Sendtype       *int32  `protobuf:"varint,4,req,name=sendtype" json:"sendtype,omitempty"`
	Imtype         *int32  `protobuf:"varint,5,req,name=imtype" json:"imtype,omitempty"`
	Iminfo         *string `protobuf:"bytes,6,opt,name=iminfo" json:"iminfo,omitempty"`
	Filetpath      *string `protobuf:"bytes,7,opt,name=filetpath" json:"filetpath,omitempty"`
	Createtime     *int32  `protobuf:"varint,8,opt,name=createtime" json:"createtime,omitempty"`
	Groupmessageid *int32  `protobuf:"varint,9,opt,name=groupmessageid" json:"groupmessageid,omitempty"`
	Sccidrevived   *int32  `protobuf:"varint,10,opt,name=sccidrevived" json:"sccidrevived,omitempty"` //在群组消息中 被发送人的ID
}

func (x *SccIMPush) Reset() {
	*x = SccIMPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sjd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SccIMPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SccIMPush) ProtoMessage() {}

func (x *SccIMPush) ProtoReflect() protoreflect.Message {
	mi := &file_sjd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SccIMPush.ProtoReflect.Descriptor instead.
func (*SccIMPush) Descriptor() ([]byte, []int) {
	return file_sjd_proto_rawDescGZIP(), []int{0}
}

func (x *SccIMPush) GetMessageid() int32 {
	if x != nil && x.Messageid != nil {
		return *x.Messageid
	}
	return 0
}

func (x *SccIMPush) GetFromsccid() int32 {
	if x != nil && x.Fromsccid != nil {
		return *x.Fromsccid
	}
	return 0
}

func (x *SccIMPush) GetTosccid() int32 {
	if x != nil && x.Tosccid != nil {
		return *x.Tosccid
	}
	return 0
}

func (x *SccIMPush) GetSendtype() int32 {
	if x != nil && x.Sendtype != nil {
		return *x.Sendtype
	}
	return 0
}

func (x *SccIMPush) GetImtype() int32 {
	if x != nil && x.Imtype != nil {
		return *x.Imtype
	}
	return 0
}

func (x *SccIMPush) GetIminfo() string {
	if x != nil && x.Iminfo != nil {
		return *x.Iminfo
	}
	return ""
}

func (x *SccIMPush) GetFiletpath() string {
	if x != nil && x.Filetpath != nil {
		return *x.Filetpath
	}
	return ""
}

func (x *SccIMPush) GetCreatetime() int32 {
	if x != nil && x.Createtime != nil {
		return *x.Createtime
	}
	return 0
}

func (x *SccIMPush) GetGroupmessageid() int32 {
	if x != nil && x.Groupmessageid != nil {
		return *x.Groupmessageid
	}
	return 0
}

func (x *SccIMPush) GetSccidrevived() int32 {
	if x != nil && x.Sccidrevived != nil {
		return *x.Sccidrevived
	}
	return 0
}

var File_sjd_proto protoreflect.FileDescriptor

var file_sjd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6a, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x63, 0x63,
	0x22, 0xc9, 0x01, 0x0a, 0x09, 0x53, 0x63, 0x63, 0x49, 0x4d, 0x50, 0x75, 0x73, 0x68, 0x12, 0x11,
	0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x12, 0x11, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x73, 0x63, 0x63, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x05, 0x12, 0x0f, 0x0a, 0x07, 0x74, 0x6f, 0x73, 0x63, 0x63, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x05, 0x12, 0x10, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x12, 0x0e, 0x0a, 0x06, 0x69, 0x6d, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x12, 0x0e, 0x0a, 0x06, 0x69, 0x6d, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x12, 0x11, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x74,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x12, 0x12, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x12, 0x16,
	0x0a, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x69, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x12, 0x14, 0x0a, 0x0c, 0x73, 0x63, 0x63, 0x69, 0x64, 0x72,
	0x65, 0x76, 0x69, 0x76, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
}

var (
	file_sjd_proto_rawDescOnce sync.Once
	file_sjd_proto_rawDescData = file_sjd_proto_rawDesc
)

func file_sjd_proto_rawDescGZIP() []byte {
	file_sjd_proto_rawDescOnce.Do(func() {
		file_sjd_proto_rawDescData = protoimpl.X.CompressGZIP(file_sjd_proto_rawDescData)
	})
	return file_sjd_proto_rawDescData
}

var file_sjd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sjd_proto_goTypes = []interface{}{
	(*SccIMPush)(nil), // 0: scc.SccIMPush
}
var file_sjd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sjd_proto_init() }
func file_sjd_proto_init() {
	if File_sjd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sjd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SccIMPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sjd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sjd_proto_goTypes,
		DependencyIndexes: file_sjd_proto_depIdxs,
		MessageInfos:      file_sjd_proto_msgTypes,
	}.Build()
	File_sjd_proto = out.File
	file_sjd_proto_rawDesc = nil
	file_sjd_proto_goTypes = nil
	file_sjd_proto_depIdxs = nil
}
